newspaper/NewsPaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('', include('news.urls')),
    path('accounts/', include('allauth.urls')),
    path('profile/', include('sign.urls')),
]

newspaper/news/urls.py
from django.urls import path
from .views import PostsList, PostDetail, PostCreate, PostUpdate, PostDelete, SearchList

urlpatterns = [
    path('news/', PostsList.as_view(), name='post_list'),
    path('news/<int:pk>', PostDetail.as_view(), name='news_detail'),
    path('news/search/', SearchList.as_view(), name='search_list'),
    path('news/create/', PostCreate.as_view(), name='post_create'),
    path('news/<int:pk>/edit/', PostUpdate.as_view(), name='post_update'),
    path('news/<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
    path('articles/<int:pk>', PostDetail.as_view(), name='articles_detail'),
    path('articles/create/', PostCreate.as_view(), name='post_create'),
    path('articles/<int:pk>/edit/', PostUpdate.as_view(), name='post_update'),
    path('articles/<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
]

newspaper/sign/urls.py
from django.urls import path
from .views import ProfileView
from .views import upgrade_me

urlpatterns = [
    path('', ProfileView.as_view()),
    path('sign/upgrade/', upgrade_me, name='upgrade')
]

newspaper/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Author(models.Model):
    rating = models.IntegerField(default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    def update_rating(self):
        Summary = 0
        sample = self.post_set.all()

        for i in sample:
            Summary += 3 * i.rating
            sum_com = 0
            sub_sample = i.comment_set.all()
            for j in sub_sample:
                sum_com += j.rating
            Summary += sum_com
        sample = self.user.comment_set.all()

        for i in sample:
            Summary += i.rating

        self.rating = Summary
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=63, unique=True)

    def __str__(self):
        return self.name.title()


class Post(models.Model):
    is_article = models.BooleanField(default=False)
    title = models.CharField(max_length=63)
    time_in = models.DateTimeField(auto_now_add=True)
    content = models.TextField(default="Место для текста")
    rating = models.IntegerField(default=0)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    category = models.ManyToManyField(Category, through='PostCategory')

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        if len(self.content) < 125:
            prw = self.content
        else:
            prw = self.content[:124] + '...'
        return prw

    def __str__(self):
        return f'{self.title.title()}: {self.content[:20]}'

    def get_absolute_url(self):
        if self.is_article:
            return reverse('articles_detail', args=[str(self.id)])
        return reverse('news_detail', args=[str(self.id)])


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    time_in = models.DateTimeField(auto_now_add=True)
    reply = models.CharField(max_length=255)
    rating = models.IntegerField(default=0)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

newspaper/sign/models.py
from django.db import models

# Create your models here.

newspaper/news/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'author',
            'category',
        ]

newspaper/sign/forms.py
from allauth.account.forms import SignupForm
from django.contrib.auth.models import Group


class CommonSignupForm(SignupForm):

    def save(self, request):
        user = super(CommonSignupForm, self).save(request)
        common_group = Group.objects.get(name='common')
        common_group.user_set.add(user)
        return user

newspaper/news/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import ValidationError
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post
from .filters import PostFilter
from .forms import PostForm


class PostsList(ListView):
    model = Post
    ordering = '-time_in'
    template_name = 'posts.html'
    context_object_name = 'posts'
    paginate_by = 10


class SearchList(ListView):
    model = Post
    ordering = '-time_in'
    template_name = 'search.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class PostDetail(DetailView):
    model = Post
    template_name = 'post.html'
    context_object_name = 'post'


class PostCreate(PermissionRequiredMixin, CreateView):
    permission_required = ('news.add_post')
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'

    def form_valid(self, form):
        if 'articles' in self.request.path:
            post = form.save(commit=False)
            post.is_article = True
        return super().form_valid(form)


class PostUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = ('news.change_post')
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'

    def form_valid(self, form):
        post = form.save(commit=False)
        if ('news' in self.request.path) and post.is_article:
            raise ValidationError(
                "Вы пытаетесь редактировать статью как новость."
            )
        elif ('articles' in self.request.path) and not post.is_article:
            raise ValidationError(
                "Вы пытаетесь редактировать новость как статью."
            )
        else:
            return super().form_valid(form)


class PostDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('news.delete_post')
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('post_list')

newspaper/sign/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_authors'] = not self.request.user.groups.filter(name='authors').exists()
        return context


@login_required
def upgrade_me(request):
    user = request.user
    premium_group = Group.objects.get(name='authors')
    if not request.user.groups.filter(name='authors').exists():
        premium_group.user_set.add(user)
    return redirect('/profile/')

newspaper/templates/post.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}
<h1>{{ post.title|censor  }}</h1>
{{ post.time_in|date:'d.m.Y' }}
<br>
{{ post.content|censor  }}
{% endblock content %}

newspaper/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление публикации</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Вы уверены удалить "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

newspaper/templates/post_edit.html
{% extends 'flatpages/default.html' %}


{% block content %}
<h1>Публикация</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

newspaper/templates/posts.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
    Posts
{% endblock title %}

{% block content %}
    <h1>Все публикации</h1>

    <hr>
    {% if posts %}
        <table>
            <tr>
                <td>
                    Заголовок
                </td>
                <td>
                    Дата публикации
                </td>
                <td>
                    Анонс
                </td>
            </tr>
            {% for post in posts %}
            <tr>
                <td>{{ post.title|censor }}</td>
                <td>{{ post.time_in|date:'d.m.Y' }} </td>
                <td>{{ post.content|truncatechars:20|censor }}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Публикаций нет!</h2>
    {% endif %}


    {% if page_obj.has_previous %}
        <a href="?page=1">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

newspaper/templates/profile.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h2>Страница авторизованного пользователя {{request.user.username}}</h2>
<div> Здесь может содержаться персональная информация для каждого пользователя </div>

<button> <a href="/accounts/logout/">Выйти</a> </button>
{% if is_not_authors %}
<button> <a href="sign/upgrade/"> Хочу стать автором!</a> </button>
{% endif %}
{% endblock %}

newspaper/templates/search.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load custom_tags %}

{% block title %}
    Search
{% endblock title %}

{% block content %}
    <h1>Публикации</h1>
    <form action="" method="get">
        <p>
            <label for="id_title__icontains">Title contains:</label>
            <input type="text" name="title__icontains" id="id_title__icontains">
        </p>
        <p>{{ filterset.form.author }}</p>
        <p>
            <label for="id_time_in">Start date:</label>
            <input type="date" name="time_in" id="id_time_in"
                   value="2023-03-10">
        </p>

        {# Добавим кнопку отправки данных формы #}
        <input type="submit" value="Найти" />
    </form>

    <hr>
    {% if posts %}
        <table>
            <tr>
                <td>
                    Заголовок
                </td>
                <td>
                    Дата публикации
                </td>
                <td>
                    Анонс
                </td>
            </tr>
            {% for post in posts %}
            <tr>
                <td>{{ post.title|censor }}</td>
                <td>{{ post.time_in|date:'d.m.Y' }} </td>
                <td>{{ post.content|truncatechars:20|censor }}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Публикаций нет!</h2>
    {% endif %}

    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}